- CVARS.txt
Current defaults means staying on the leaderboard for 20 seconds at the end of each ten rounds.  Especially due to the fact that kills, assists and deaths aren't recorded this means you just wait for that time.
> Add in mp_match_restart_delay to cvars.txt

- addons/sourcemod/scripting/ttt/ttt_shop.sp
Fix for ttt_credits_timer not taking effect when ttt_credits_interval is at 60 seconds.
> Fix for players not earning credits every minute.

- addons/sourcemod/scripting/ttt/ttt_shop.sp
Ensures the credits timer is repeats for as long as the player is valid and alive.
> Fix for credits timer not repeating.

- addons/sourcemod/scripting/include/ttt.inc
- addons/sourcemod/scripting/ttt/ttt.sp
- addons/sourcemod/translations/ttt.phrases.txt
Added g_iConfig[bLogsDeadOnly] initialization on cvars read.
Added g_iConfig[bLogsNotifyAlive] to notify all players when someone is alive and using logs of current round.
Added phrase "watching logs alive" to translations.
> Logs dead only fix and feature

- addons/sourcemod/translations/ttt.phrases.txt
Use correct color for "watching logs alive" phrase to resolve the following error:
[SM] Exception reported: Using two team colors in one message is not allowed
> Use correct color for "watching logs alive" phrase

- addons/sourcemod/translations/ttt.phrases.txt
L 07/01/2017 - 14:39:11: [SM] Exception reported: Language phrase "Item bought! (NEW)" not found (arg 5)
L 07/01/2017 - 14:39:11: [SM] Blaming: cs-ttt\ttt_shop.smx
This was originally added here https://github.com/Bara20/TroubleinTerroristTown/commit/fb6c28e69ecc554b1e766d55e87cf545558f7afe, but I assume accidentally removed here: https://github.com/Bara20/TroubleinTerroristTown/commit/88c370395be1ce76dd94e8c2e649a01719361b14
> Add missing language phrase "Item bought! (NEW)"

- addons/sourcemod/scripting/ttt/ttt.sp
It's irrelevant to know if an admin is watching logs whilst alive during a pre-round since the logs are for the previous round (which everyone has access to).
> Prevents watching logs notification in pre-round

- addons/sourcemod/scripting/ttt/ttt_radio.sp
Change Code to remove red color on Traitors or else traitors who use the radio will give away that they are a traitor.
> Update ttt_radio.sp remove red Color for Traitor

- addons/sourcemod/scripting/ttt/ttt_radio.sp
Dead players currently can ghost.
> Prevent dead players from using radio

- CREDITS.md
I can't actually remember a time where the gproject URL was used, :)
> Update CLWO URL

- addons/sourcemod/scripting/ttt/core/config.sp
- addons/sourcemod/scripting/ttt/core/globals.sp
- addons/sourcemod/scripting/ttt/ttt.sp
- addons/sourcemod/translations/pt/ttt.phrases.txt
- addons/sourcemod/translations/ttt.phrases.txt
By default everyone will lose karma if they kill the wrong person.
If they disable the new cvar, it will enable the feature that it will avoid losing karma if you kill the last 2 persons that shoot at you.
Also added 2 extra verifications to avoid suicide.
I haven't tested this with the cvar, but I've been using this for a while and it's working.
> Feature to avoid losing karma (Issue #179)

- addons/sourcemod/scripting/include/ttt.inc
- addons/sourcemod/scripting/ttt/core/config.sp
- addons/sourcemod/scripting/ttt/core/globals.sp
- addons/sourcemod/scripting/ttt/core/natives.sp
- addons/sourcemod/scripting/ttt/ttt.sp
- addons/sourcemod/scripting/ttt/ttt_shop.sp
- addons/sourcemod/translations/ttt.phrases.txt
This is the Silent ID feature.
New CVARs:
**"ttt_silent_id"** "0"- Enable/Disable Silent ID feature
**"ttt_silent_id_color"** "1"- Enable/Disable coloring the body when Silent ID.
**"ttt_silent_id_roles"** "14"- Roles allowed to silent ID. See [Masks](https://github.com/Bara/TroubleinTerroristTown/wiki/CVAR-Masks) for more detailed information.
**"ttt_silent_id_rewards"** "1"- Should the player be rewarded when using Silent ID?
This feature allow players to inspect a body without notifying others. By holding Walk (+speed) + Use (+use) on a body.
More information: https://skynetgaming.net/forums/topic/10391-request-silent-id-bodies/
> Silent ID Feature

- addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp
L 10/17/2018 - 00:39:52: [SM] Call stack trace:
L 10/17/2018 - 00:39:52: [SM]   [0] GetEntPropString
L 10/17/2018 - 00:39:52: [SM]   [1] Line 758, /home/travis/build/Bara/TroubleinTerroristTown/addons/sourcemod/scripting/include/entity.inc::GetEntityClassname
L 10/17/2018 - 00:39:52: [SM]   [2] Line 540, addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp::OnPlayerRunCmd
L 10/17/2018 - 00:45:34: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2018 - 00:45:34: [SM] Blaming: ttt\ttt_c4_jihad.smx
L 10/17/2018 - 00:45:34: [SM] Call stack trace:
> fix error.

- addons/sourcemod/scripting/ttt/ttt_shop.sp
This merge request updates the ttt_shop plugin by adding the functionality necessary to record player item purchases to the round logs. It was originally a request of EdgeGamers CSLE and the original message I received will be posted below:
> When a Traitor purchases a weapon, add it to the sm_logs - this is because sometimes a traitor is killed when they are caught purchasing a Traitor-Only weapon, but admins can't find out if that was the case.
The ttt_shop plugin will still compile without any errors nor warnings.
> Log Round Shop Purchases

- addons/sourcemod/scripting/ttt/ttt_traitordoors.sp
This pull request adds an optional configuration and functionality to grant admins and servers the ability to review the usage of traitor doors in post-game logs.
This is a feature that's been requested by several of the eGO server players plus one member of leadership in the community.
> Log Traitor Door Usage

- addons/sourcemod/scripting/ttt/ttt_shop.sp
The very early opinion from eGO is that the logging of all purchases is annoying (think of 25 innocents buying armor at second 0 filling up the logs. This PR changes this to create a new configuration option (defaulted at 2) that allows server owners to configure which purchases should be logged.
A setting of 0 disables shop logging. A setting of 1 enabled all purchases to be logged. A setting of 2 only logs purchases from special players (traitors, detectives).
> Shop Log Configuration

- addons/sourcemod/scripting/ttt/ttt_teleporter.sp
This pull request adds an additional configuration for teleporters which will limit the amount of times a traitor can purchase the item during a single round.
It has been heavily requested to nerf the teleporter as a lot of people find that it's currently overpowered, and I believe this config in general will be helpful.
> Configuration for Teleporter Purchases

- addons/sourcemod/scripting/include/ttt_weapons.inc
- addons/sourcemod/scripting/ttt/ttt_weapons.sp
Add Option to use Bumpmines as Innocent
> Add Option to use Bumpmines as Innocent

- .github/workflows/master.yml
- addons/sourcemod/scripting/vphysics_crash_fix.sp
A plugin I've worked on these past few weeks, should be able to mitigate most vphysics crashes from ragdolls.
Works by storing death locations with a time, then before a client should die, it iterates through the recent deaths, and if the current death loc is too close, the client shall be pushed away from the nearby deaths before they are killed.
The side effects of this pushing are not too visible, as they are only pushed on average 32 units (the size of a player).
> Release VPhysics Crash Fix

- addons/sourcemod/scripting/ttt/ttt_rdm.sp
If you have the convar ``ttt_roundend_dm "1"`` enabled, then kills are reported as RDM at the end of the round. This will ensure this does not happen.
> Fix RDM Manager reporting kills post round.

- addons/sourcemod/scripting/ttt/ttt_shop.sp
If you have the convar ``ttt_roundend_dm "1"`` enabled, then kills are counted as in round kills and reward players credits for ID'ing other T buddies etc. This will ensure this does not happen.
> Fixed credits being given when round is not active.

- addons/sourcemod/scripting/ttt/core/sql.sp
- addons/sourcemod/scripting/ttt/rdm/database.sp
- addons/sourcemod/scripting/ttt/ttt.sp
- addons/sourcemod/scripting/ttt/ttt_sql.sp
Not yet been able to replicate the error but added some extra logging to see where it is going wrong also made the ttt player id unsigned though it shouldn't matter.
L 08/23/2020 - 10:03:25: [ttt/ttt_rdm.smx] DbCallback_InsertDeath: Out of range value for column 'victim_id' at row 1
This error generally means the value is out of range, so would seem that `TTT_GetPlayerID` is returning -1 or something or other, which is the cause of the problem, shall try reproducing on a local server again.
We may need to validate Player ID's in `SQL_OnClientPutInServer` incase -1 is returned.
To also look to fix this I have made the `ttt` tables `id` column be unsigned to match that of RDM but noone should really be having that many players in there database anyway.
> Preemptive fixes for out of range victim and attacker id's #480

- addons/sourcemod/scripting/ttt/ttt_bodies.sp
- addons/sourcemod/translations/ttt.phrases.txt
- addons/sourcemod/translations/ttt_rdm.phrases.txt
Replaced gendered (he/him/his) pronouns in `ttt.phrases.txt` with gender-neutral (they/them/theirs) pronouns. Also fixed small pronoun-typo in `ttt_rdm.phrases.txt`.
> Fix English (en) pronouns
