TroubleInTerroristTown/Public

- addons/sourcemod/scripting/include/ttt.inc
- addons/sourcemod/scripting/include/ttt_shop.inc
- addons/sourcemod/scripting/ttt/core/globals.sp
- addons/sourcemod/scripting/ttt/core/natives.sp
- addons/sourcemod/scripting/ttt/ttt.sp
- addons/sourcemod/scripting/ttt/ttt_shop.sp
> Moved Credits to Shop

- addons/sourcemod/scripting/ttt/ttt.sp
- addons/sourcemod/scripting/ttt/ttt_taser.sp
- addons/sourcemod/translations/ttt.phrases.txt
This implements https://github.com/Bara20/TroubleinTerroristTown/issues/49
And implements https://github.com/Bara20/TroubleinTerroristTown/issues/43
> Implemented LogAction on the main plugin and Taser broadcast result

- addons/sourcemod/scripting/ttt/ttt.sp
- addons/sourcemod/scripting/ttt/ttt_iceknife.sp
- addons/sourcemod/scripting/ttt/ttt_taser.sp
- addons/sourcemod/translations/ttt.phrases.txt
This adds HookClient() which allows  the plugin to rehook the client on connecting and on plugin reloads
> Make plugins compatible with late loading

- addons/sourcemod/scripting/include/ttt.inc
- addons/sourcemod/scripting/ttt/core/globals.sp
- addons/sourcemod/scripting/ttt/ttt.sp
Haven't tried with a large amount of players yet, but it should work. (Max player amount while testing was 5)
> Role choosing

- addons/sourcemod/scripting/ttt/ttt_wallhack.sp
Fix for wallhack not being listed in the detective's shop menu.
> Fix for wallhack not showing in detective's menu.

- addons/sourcemod/scripting/ttt/ttt_id.sp
[SM] Plugin "ttt\ttt_id.smx" encountered error 23: Native detected error
L 08/22/2017 - 19:02:46: [SM] Invalid timer handle 42470418 (error 3) during timer end, displayed function is timer callback, not the stack trace
L 08/22/2017 - 19:02:46: [SM] Unable to call function "Timer_Cooldown" due to above error(s).
> fix errors

- CREDITS.md
Also updated the Phoenix Gaming Network link to the Frag Haven link (we're in the process of switching the community to a new name).
Hope this is okay. Also would like to be put back into the contributors section (I haven't made any since the switch from Git.tf to GitHub, though I plan to take on some of the bigger tasks/issues soon).
Sorry for my absence guys.
> Update CREDITS.md with new links for me

- addons/sourcemod/scripting/ttt/ttt_traps.sp
Fixed traps & buttons that use filter_activators. All credit to R3TROATTACK for showing me how :)
> ttt_traps initial files

- CREDITS.md
> Amend CREDITS.md

- addons/sourcemod/scripting/ttt/ttt_iceknife.sp
Added fix as discussed in Discord
> Fixed issue where player did not lose Ice Knife into the next round

- addons/sourcemod/scripting/ttt/ttt.sp
Fixing a small bug where it would print to the victim instead of the attacker.
> The message should print to the attacker.

- addons/sourcemod/translations/tripmines.phrases.txt
I have no idea of a portuguese translation for "tripmine" so anyway.
> pt translation

- PUSH
- addons/sourcemod/scripting/include/ttt.inc
- addons/sourcemod/scripting/ttt/core/config.sp
- addons/sourcemod/scripting/ttt/core/globals.sp
- addons/sourcemod/scripting/ttt/ttt.sp
- addons/sourcemod/scripting/ttt/ttt_grabbermod.sp
- addons/sourcemod/scripting/ttt/ttt_icon.sp
- addons/sourcemod/scripting/ttt/ttt_radio.sp
- addons/sourcemod/scripting/ttt/ttt_shop.sp
- addons/sourcemod/scripting/ttt/ttt_shop_discount.sp
@good-live required for this commit: https://github.com/Bara/TroubleinTerroristTown/commit/e658e528152cb492a763ffa226cc1636407b6e96
This also fix 2 builds per commit in a pull requests.
> Replace TTT_Has*Flags with TTT_CheckCommandAccess

- addons/sourcemod/scripting/include/ttt.inc
Store the RGB values in an array, then read it out
> Remove code repetition

- addons/sourcemod/scripting/ttt/ttt_missiles.sp
Un used and build not package
DowDownloading *.com/sound/weapons/rpg/rocket1.wav.bz2.
Error downloading *.com/sound/weapons/rpg/rocket1.wav.bz2
Downloading *.com/sound/weapons/rpg/rocket1.wav.
Error downloading *.com/sound/weapons/rpg/rocket1.wav
Downloading *.com/models/weapons/w_models/w_rocket.mdl.bz2.
Error downloading *.com/models/weapons/w_models/w_rocket.mdl.bz2
Downloading *.com/models/weapons/w_models/w_rocket.mdl.
Error downloading *.com/models/weapons/w_models/w_rocket.mdl
Downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vmt.bz2.
Error downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vmt.bz2
Downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vmt.
Error downloading …
> Remove not packaged

- addons/sourcemod/scripting/ttt/ttt_icon.sp
If Icon is empty, don't download and attempt to make one
> If Icon is empty, don't download and attempt to make one

- addons/sourcemod/scripting/ttt/ttt_taser.sp
- ci/build.sh
- ci/test.sh
> Keep taser after round end

- addons/sourcemod/scripting/ttt/ttt.sp
- addons/sourcemod/scripting/ttt/ttt_dnascanner.sp
This pull request resolves an issue in the original ttt.sp file where the OnButtonPressed callback was creating a log string but failed to submit it into the round records. This pull request also optimizes console variable usage in the ttt_dnascanner.sp file.
> Simple Optimizations & Fixes

- .github/workflows/master.yml
- .travis.yml
- addons/sourcemod/scripting/ttt/ttt_shop.sp
I suggest to not use it with SM 1.9
> [Shop] Update enum array to new SM standard

- addons/sourcemod/scripting/no_weapon_fix.sp
> Fix DrewViewModel based on @Cruze03 suggestion
